# Generated by Django 3.1.2 on 2020-11-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.user')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('fname', models.CharField(max_length=50)),
                ('standard', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=80)),
                ('ID', models.CharField(max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students_images')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('dob', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
