# Generated by Django 3.1.2 on 2020-11-01 10:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20201101_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountdetail',
            name='dob',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='accountdetail',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='students_images'),
            preserve_default=False,
        ),
    ]
